-- SQL Schema for Supabase
-- Run these in the Supabase SQL Editor

-- 1. Create Logs Table
CREATE TABLE IF NOT EXISTS logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  source TEXT,
  level TEXT,
  message TEXT,
  details TEXT
);

-- 2. Create Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  description TEXT,
  image TEXT,
  category TEXT,
  stock INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT,
  total DOUBLE PRECISION NOT NULL,
  status TEXT DEFAULT 'PENDING',
  items JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Seed Data (Optional)
INSERT INTO products (name, price, description, image, category, stock)
VALUES 
('iPhone 15 Pro', 25000000, 'Flagship Apple smartphone', 'https://picsum.photos/seed/iphone/400/400', 'Mobile', 10),
('MacBook M3', 45000000, 'Powerful laptop for pros', 'https://picsum.photos/seed/macbook/400/400', 'Laptop', 5),
('AirPods Pro', 5500000, 'Noise cancelling earbuds', 'https://picsum.photos/seed/airpods/400/400', 'Accessories', 20),
('Apple Watch Ultra', 18000000, 'Rugged smartwatch', 'https://picsum.photos/seed/watch/400/400', 'Watch', 8);
